/************************************************************************
* Author  : Abdelrahman Osam Khaled
* Date	  : 10 April , 2023
* SWC	  : TIMER
* Layer   : MCAL
* Version : 2.0
*************************************************************************/

#ifndef TIMER_CONFIG_H
#define TIMER_CONFIG_H

#define TIMER0_MODE TIMER_NORMAL_MODE
#define TIMER1_MODE	TIMER_NORMAL_MODE
#define TIMER2_MODE TIMER_NORMAL_MODE
/* Options for TIMER0_MODE & TIMER2_MODE:
			TIMER_NORMAL_MODE
			TIMER_PWM_PHASE_CORRECT_TOP_8_MODE
			TIMER_CTC_TOP_OCR_MODE
			TIMER_FAST_PWM_TOP_8_MODE
	
	Options for TIMER1_MODE :
			TIMER_NORMAL_MODE
			TIMER_PWM_PHASE_CORRECT_TOP_8_MODE
			TIMER_PWM_PHASE_CORRECT_TOP_9_MODE
			TIMER_PWM_PHASE_CORRECT_TOP_10_MODE
			TIMER_CTC_TOP_OCR_MODE
			TIMER_FAST_PWM_TOP_8_MODE
			TIMER_FAST_PWM_TOP_9_MODE
			TIMER_FAST_PWM_TOP_10_MODE
			TIMER_PWM_PHASE_FREQ_CORRECT_TOP_ICR_MODE
			TIMER_PWM_PHASE_FREQ_CORRECT_TOP_OCR_MODE
			TIMER_PWM_PHASE_CORRECT_TOP_ICR_MODE
			TIMER_PWM_PHASE_CORRECT_TOP_OCR_MODE
			TIMER_CTC_TOP_ICR_MODE
			TIMER_FAST_PWM_TOP_ICR_MODE
			TIMER_FAST_PWM_TOP_OCR_MODE
	*/
	
#define TIMER0_OUTPUT_MODE	TIMER_OC_DISCONNECTED
#define TIMER1A_OUTPUT_MODE	TIMER_OC_DISCONNECTED
#define TIMER1B_OUTPUT_MODE	TIMER_OC_DISCONNECTED
#define TIMER2_OUTPUT_MODE	TIMER_OC_DISCONNECTED
/* Options :
			TIMER_OC_DISCONNECTED
			TIMER_NON_INVERTED
			TIMER_INVERTED
	*/
	
#define TIMER0_PRESCALER  TIMER_PRESCALER_8
#define TIMER1_PRESCALER  TIMER_PRESCALER_8
#define TIMER2_PRESCALER  TIMER_PRESCALER_8

/* Options for TIMER0_PRESCALER & TIMER1_PRESCALER:
			TIMER_STOPPED
			TIMER_NO_PRESCALER
			TIMER_PRESCALER_8
			TIMER_PRESCALER_64
			TIMER_PRESCALER_256
			TIMER_PRESCALER_1024
			
	* Options for TIMER2_PRESCALER :
			TIMER_STOPPED
			TIMER_NO_PRESCALER
			TIMER_PRESCALER_8
			TIMER_PRESCALER_32
			TIMER_PRESCALER_64
			TIMER_PRESCALER_128
			TIMER_PRESCALER_256
			TIMER_PRESCALER_1024
	*/

#endif
