/*******************************************************************
* Author 		: Abdelrahman Osam Khaled
* Creation Date : 17 April , 2023
* SWC			: SPI
* Layer			: MCAL
* Version		: V1.0
*********************************************************************/

#ifndef SPI_CONFIG_H
#define SPI_CONFIG_H

#define CLOCK_POLARITY_SELECTION LEADING_RISING_TRAILING_FALLING_MODE
/* Options :
			LEADING_RISING_TRAILING_FALLING_MODE
			LEADING_FALLING_TRAILING_RISING_MODE
	*/

#define CLOCK_PHASE_SELECTION SAMPLE_LEADING_SETUP_TRAILING_MODE
/* Options :
			SAMPLE_LEADING_SETUP_TRAILING_MODE
			SETUP_LEADING_SAMPLE_TRAILING_MODE
	*/

#define CLOCK_RATE_SELECTION FREQUENCY_DIVIDE_BY_16_MODE	
/* Options :
			FREQUENCY_DIVIDE_BY_4_MODE
			FREQUENCY_DIVIDE_BY_16_MODE
			FREQUENCY_DIVIDE_BY_64_MODE
			FREQUENCY_DIVIDE_BY_128_MODE
			FREQUENCY_DIVIDE_BY_2_MODE
			FREQUENCY_DIVIDE_BY_8_MODE
			FREQUENCY_DIVIDE_BY_32_MODE
			FREQUENCY_DIVIDE_BY_64_MODE
	*/
#endif